### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by bundyboss** [wnielson/nzbverify#2]
Hi,
I've tryied your program but I've this problem:
nzbverify version 0.3.0, Copyright (C) 2014 Weston Nielson <wnielson@github>
Found 1 primary host
   news.xxxxx.com
Found 0 backup hosts
Created 2/2 threads
Parsing NZB: tests/nzbs/ubuntu-12_04-dvd-amd64_iso.nzb
Found 43 files and 2878 segments totaling 1.75 GB
Available:    0 [0.00%], Missing:    0 [0.00%], Total:    0 [0.00%]Exception in thread thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/nzbverify/nzbverify/thread.py", line 32, in run
    connection = self.server.create_connection()
  File "/home/nzbverify/nzbverify/server.py", line 37, in create_connection
    self.conf.get("use_ssl"), self.conf.get("timeout"))
  File "/home/nzbverify/nzbverify/nntp.py", line 58, in __init__
    if 'STARTTLS' in self.getcapabilities():
TypeError: argument of type 'NoneType' is not iterable

Available:    0 [0.00%], Missing:    0 [0.00%], Total:    0 [0.00%]Exception in thread thread-0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/nzbverify/nzbverify/thread.py", line 32, in run
    connection = self.server.create_connection()
  File "/home/nzbverify/nzbverify/server.py", line 37, in create_connection
    self.conf.get("use_ssl"), self.conf.get("timeout"))
  File "/home/nzbverify/nzbverify/nntp.py", line 58, in __init__
    if 'STARTTLS' in self.getcapabilities():
TypeError: argument of type 'NoneType' is not iterable

Have you an idea?

**Comment by wnielson** [comment]
This version is not stable yet.  Try the version on [PyPi](https://pypi.python.org/pypi/nzbverify) and see if that works for you.

**Comment by bundyboss** [comment]
Hi,
Thanks for your reply. I was using the github version because is in 0.3.0
instead of the version in Pypi who is in 0.2.0!
I'll test this version and come back to you.
Regards

2017-05-03 15:21 GMT+02:00 Weston Nielson <notifications@github.com>:

**Comment by wnielson** [comment]
I need to update the README to note that this is a work in progress and unstable at the moment.  Report back if you have issues with 0.2.0.

**Comment by bundyboss** [comment]
Problem is different but perhaps due to my use:
nzbverify -sxxxx.xxxx.com -uxxxx@xxx.com -p -P119 -n1 tests/nzbs/ubuntu-12_04-dvd-amd64_iso.nzb
nzbverify version 0.2.0, Copyright (C) 2012 Weston Nielson <wnielson@github>
Password:
Created 1 threads
Parsing NZB: tests/nzbs/ubuntu-12_04-dvd-amd64_iso.nzb
Found 43 files and 2878 segments totalling 1.75 GB
Available:    0 [0.00%], Missing:    0 [0.00%], Total:    0 [0.00%]Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/nzbverify-0.2.0/nzbverify/thread.py", line 26, in run
    self.server = nntp.NNTP(**self.credentials)
  File "/home/nzbverify-0.2.0/nzbverify/nntp.py", line 58, in __init__
    if 'STARTTLS' in self.getcapabilities():
TypeError: argument of type 'NoneType' is not iterable

Available:    0 [0.00%], Missing:    0 [0.00%], Total:    0 [0.00%]^C
Stopping threads...done

I'm sure of the username and password given (but login have special character like @ and )

Thanks for your help

**Comment by wnielson** [comment]
I just added [version 0.2.0](https://github.com/wnielson/nzbverify/tree/v0.2.x) to Github.  Can you please checkout that copy and give it a go?

**Comment by bundyboss** [comment]
Thanks a lot it's working fine with this version but It's not the version 0.2.0 but 0.2.1

**Comment by wnielson** [comment]
Thanks for testing and reporting this.  I've uploaded the fixed version to PyPi.
